version: '3.1'

services:
  webserver:
    image: cienrxs/webserver:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8080:80
    volumes:
      - /home/html:/var/www/html
    networks:
      - kdsp

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - kdsp

networks:
  kdsp:
volumes:
  portainer_data:
